### ISSUE TITLE
Outdated CURL urls in init-letsencrypt.sh

### ISSUE THREAD

**Issue by rajahks** [ermissa/django-docker-setup#2]
The url's used by curl to download the files in `init-letsencrypt.sh` seem to be outdated. Fetching them directly gives `Not found`. I used the ones at the below location and it worked for me. Also the script has slightly changed.

https://github.com/wmnnd/nginx-certbot/blob/master/init-letsencrypt.sh

**Comment by ermissa** [comment]
Sorry, I saw your issues today. Thank you for informing me.

**Comment by ujaved977** [comment]
Hello,
cannot load certificate "/etc/letsencrypt/live/data-style.de/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/data-style.de/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
any information about this error? I followed the instructions and my domain has correct A record
